version: '3'

services:
     
   emailcheck:
     build: ./emailcheck
     ports:
     - "9000:9000"

   passwordcheck:
     build: ./passwordcheck
     ports:
     - "9001:9001"
     
   roles:
     build: ./roles
     ports:
     - "9002:9002"     
